export const AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING";
export const AUTH_TOKEN_INCORRECT = "AUTH_TOKEN_INCORRECT";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const NO_TARGET_USER_FOR_CHAT = "NO_TARGET_USER_FOR_CHAT";
